apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment  
  labels: 
    app: nginx  
    tier: frontend 
spec: 
  replicas: 5
  selector: 
    matchLabels: 
      tier: frontend 
      app: nginx   
  template: 
    metadata: 
      labels:
        tier: frontend 
        app: nginx    
    spec: 
      containers: 
      - name: nginx 
        image: tomcat 
        ports: 
        - containerPort: 80 
---
apiVersion: v1
kind: Service 
metadata: 
  name: nginx-service
spec: 
  selector: 
    app: nginx  
    tier: frontend
  ports: 
  - name: name-of-service-port 
    protocol: TCP 
    port: 80
    targetPort: 80