apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment  
  labels: 
    app: nginx  
    tier: frontend 
spec: 
  replicas: 20
  selector: 
    matchLabels: 
      tier: frontend 
      app: nginx   
  template: 
    metadata: 
      labels:
        tier: frontend 
        app: nginx    
    spec: 
      containers: 
      - name: nginx 
        image: tomcat 
        ports: 
        - containerPort: 80 
