apiVersion: v1
kind: Pod
metadata: 
  name: envar-demo 
spec:
  containers:
  - name: envar-demo-container
    image: nginx 
    env: 
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FIREWALL
      value: "such a sweet sorrow" 