apiVersion: v1
kind: Secret 
metadata: 
  name: secret-basic-auth
data:
  username: bmlraGlsY2hhbmRyYQo=
  password: Y2hhbmRyYTEyMwo=
---
apiVersion: v1
kind: Pod
metadata: 
  name: secret-pod
spec: 
  containers:
  - name: secret-pod 
    image: nginx 
    envFrom: 
    - secretRef:
        name: secret-basic-auth 